{
 "title": "Consul Kubernetes Example",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "apiGroup",
    "query": "registry/apiregistration.k8s.io/apiservices/"
   }
  ]
 },
 "panels": [
  {
   "title": "apiVersion",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "legendFormat": "{{ apiVersion }}",
     "target": "registry/apiregistration.k8s.io/apiservices/${apiGroup}/",
     "type": "tags"
    }
   ]
  },
  {
   "title": "Name",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "legendFormat": "{{ name }}",
     "target": "registry/apiregistration.k8s.io/apiservices/${apiGroup}/",
     "type": "tags"
    }
   ]
  },
  {
   "title": "versionPriority",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "registry/apiregistration.k8s.io/apiservices/${apiGroup}/spec/versionPriority",
     "type": "get"
    }
   ]
  },
  {
   "title": "version / versionPriority",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "legendFormat": "{{ spec.version }} / {{ spec.versionPriority }}",
     "target": "registry/apiregistration.k8s.io/apiservices/${apiGroup}/",
     "type": "tagsrec"
    }
   ]
  },
  {
   "title": "group / groupPriorityMinimum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "legendFormat": "{{ spec.group }} / {{ spec.groupPriorityMinimum }}",
     "target": "registry/apiregistration.k8s.io/apiservices/${apiGroup}/",
     "type": "tagsrec"
    }
   ]
  },
  {
   "title": "apiGroup Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 4 },
   "targets": [
    {
     "columns": "../apiVersion,../name,../spec/version,../spec/versionPriority,../spec/group,../spec/groupPriorityMinimum",
     "target": "registry/apiregistration.k8s.io/apiservices/*/name",
     "type": "get"
    }
   ]
  }
 ]
}